# Generated by Django 3.0.6 on 2020-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
                ('pub_data', models.DateTimeField(blank='True', null='True')),
            ],
        ),
    ]
