# Generated by Django 3.0.6 on 2020-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_text',
            field=models.CharField(default='ewe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_title',
            field=models.CharField(default='eweds', max_length=24),
            preserve_default=False,
        ),
    ]
