# Generated by Django 3.0.6 on 2020-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200601_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='s', upload_to=''),
            preserve_default=False,
        ),
    ]
